### ISSUE TITLE
WordPress can't seem to find namespace or element in directory

### ISSUE THREAD

**Issue by corydhmiller** [RedAntNL/twig-components#3]
Just recently been playing around with Twig and Twig Components here, and there seems to be some issues when using WordPress and `functions.php`, where I'm instantiating Components.

Here's the code I'm using, _nearly_ straight from the readme:

```
//
// functions.php
//

/* 
Set vars to respective locations
Results in:
     [site url]/wp-content/themes/my-theme/templates
     [site url]/wp-content/themes/my-theme/templates/components
*/
$templateDir = get_template_directory() . "/templates"; 
$componentsDir = get_template_directory() . "/templates/components";

// Setup the loader
$loader = new \Twig\Loader\FilesystemLoader($templateDir);
$loader->addPath($componentsDir, "Ui"); 
$twig = new \Twig\Environment($loader);

// Initialize Twig Components registry
$componentsRegistry = new ComponentsRegistry($twig);
$componentsRegistry->addComponent('ui.button', '@Ui/elements/button');

// Add the extension to your Twig environment
$componentsExtension = new ComponentsExtension($componentsRegistry);
$twig->addExtension($componentsExtension);
```

The `button.html.twig` file is located in `[site url]/wp-content/themes/my-theme/templates/components/ui/elements/button.html.twig` but does not render with anything, including `{{ component.button({ ... }) }}`, `{{ component.ui.button({ ... }) }}`, or any variation I could try.

Not really sure what's happening here :\

**Comment by ricohumme** [comment]
Hi Cory,

Could you maybe provide some logs surrounding this issue. Maybe the registry can't actually find the path or something.
I must say, I personally haven't tried this with Wordpress yet, so I will need some time on this.
Thanks in advance.

**Comment by corydhmiller** [comment]
@ricohumme Oddly enough it's not throwing _any_ errors or producing any logs. Running `print_r($twig)` produces the following, but that's about it (replaced some of the site string with `[...]`).

It seems like the paths are correct, but perhaps my folder stacks are incorrect?

```Twig\Environment Object ( [charset:Twig\Environment:private] => UTF-8 [loader:Twig\Environment:private] => Twig\Loader\FilesystemLoader Object ( [paths:protected] => Array ( [__main__] => Array ( [0] => [redacted]/wp-content/themes/my-theme/templates ) [Ui] => Array ( [0] => [redacted]/wp-content/themes/my-theme/templates/components ) ) [cache:protected] => Array ( ) [errorCache:protected] => Array ( ) [rootPath:Twig\Loader\FilesystemLoader:private] => [redacted] ) [debug:Twig\Environment:private] => [autoReload:Twig\Environment:private] => [cache:Twig\Environment:private] => Twig\Cache\NullCache Object ( ) [lexer:Twig\Environment:private] => [parser:Twig\Environment:private] => [compiler:Twig\Environment:private] => [baseTemplateClass:Twig\Environment:private] => \Twig\Template [globals:Twig\Environment:private] => Array ( ) [resolvedGlobals:Twig\Environment:private] => [loadedTemplates:Twig\Environment:private] => [strictVariables:Twig\Environment:private] => [templateClassPrefix:Twig\Environment:private] => __TwigTemplate_ [originalCache:Twig\Environment:private] => [extensionSet:Twig\Environment:private] => Twig\ExtensionSet Object ( [extensions:Twig\ExtensionSet:private] => Array ( [Twig\Extension\CoreExtension] => Twig\Extension\CoreExtension Object ( [dateFormats:Twig\Extension\CoreExtension:private] => Array ( [0] => F j, Y H:i [1] => %d days ) [numberFormat:Twig\Extension\CoreExtension:private] => Array ( [0] => 0 [1] => . [2] => , ) [timezone:Twig\Extension\CoreExtension:private] => [escapers:Twig\Extension\CoreExtension:private] => Array ( ) ) [Twig\Extension\EscaperExtension] => Twig\Extension\EscaperExtension Object ( [defaultStrategy:Twig\Extension\EscaperExtension:private] => html [escapers:Twig\Extension\EscaperExtension:private] => Array ( ) [safeClasses] => Array ( ) [safeLookup] => Array ( ) ) [Twig\Extension\OptimizerExtension] => Twig\Extension\OptimizerExtension Object ( [optimizers:Twig\Extension\OptimizerExtension:private] => -1 ) [RedAnt\TwigComponents\Extension] => RedAnt\TwigComponents\Extension Object ( [componentRegistry:protected] => RedAnt\TwigComponents\Registry Object ( [twig:protected] => Twig\Environment Object *RECURSION* [propertyAccessor:protected] => Symfony\Component\PropertyAccess\PropertyAccessor Object ( [magicMethodsFlags:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 3 [ignoreInvalidIndices:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 1 [ignoreInvalidProperty:Symfony\Component\PropertyAccess\PropertyAccessor:private] => [cacheItemPool:Symfony\Component\PropertyAccess\PropertyAccessor:private] => [propertyPathCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array ( [[button]] => Symfony\Component\PropertyAccess\PropertyPath Object ( [elements:Symfony\Component\PropertyAccess\PropertyPath:private] => Array ( [0] => button ) [length:Symfony\Component\PropertyAccess\PropertyPath:private] => 1 [isIndex:Symfony\Component\PropertyAccess\PropertyPath:private] => Array ( [0] => 1 ) [pathAsString:Symfony\Component\PropertyAccess\PropertyPath:private] => [button] ) ) [readInfoExtractor:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor Object ( [mutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( ) [accessorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => get [1] => is [2] => has [3] => can ) [arrayMutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => add [1] => remove ) [enableConstructorExtraction:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => [methodReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1 [magicMethodsFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 3 [propertyReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1 [inflector:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Symfony\Component\String\Inflector\EnglishInflector Object ( ) [arrayMutatorPrefixesFirst:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => add [1] => remove ) [arrayMutatorPrefixesLast:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => remove [1] => add ) ) [writeInfoExtractor:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor Object ( [mutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => set ) [accessorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => get [1] => is [2] => has [3] => can ) [arrayMutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => add [1] => remove ) [enableConstructorExtraction:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => [methodReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1 [magicMethodsFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 3 [propertyReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1 [inflector:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Symfony\Component\String\Inflector\EnglishInflector Object ( ) [arrayMutatorPrefixesFirst:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => add [1] => remove [2] => set ) [arrayMutatorPrefixesLast:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array ( [0] => set [1] => remove [2] => add ) ) [readPropertyCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array ( ) [writePropertyCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array ( ) ) [_components:protected] => Array ( [button] => @Ui/elements/button ) [components:protected] => Array ( [button] => @Ui/elements/button ) [_callStack:RedAnt\TwigComponents\Registry:private] => Array ( ) ) [globalVariable:protected] => component ) ) [initialized:Twig\ExtensionSet:private] => [runtimeInitialized:Twig\ExtensionSet:private] => [staging:Twig\ExtensionSet:private] => Twig\Extension\StagingExtension Object ( [functions:Twig\Extension\StagingExtension:private] => Array ( ) [filters:Twig\Extension\StagingExtension:private] => Array ( ) [visitors:Twig\Extension\StagingExtension:private] => Array ( ) [tokenParsers:Twig\Extension\StagingExtension:private] => Array ( ) [tests:Twig\Extension\StagingExtension:private] => Array ( ) ) [parsers:Twig\ExtensionSet:private] => [visitors:Twig\ExtensionSet:private] => [filters:Twig\ExtensionSet:private] => [tests:Twig\ExtensionSet:private] => [functions:Twig\ExtensionSet:private] => [unaryOperators:Twig\ExtensionSet:private] => [binaryOperators:Twig\ExtensionSet:private] => [globals:Twig\ExtensionSet:private] => [functionCallbacks:Twig\ExtensionSet:private] => Array ( ) [filterCallbacks:Twig\ExtensionSet:private] => Array ( ) [lastModified:Twig\ExtensionSet:private] => 0 ) [runtimeLoaders:Twig\Environment:private] => Array ( ) [runtimes:Twig\Environment:private] => Array ( ) [optionsHash:Twig\Environment:private] => ["Twig\\Extension\\CoreExtension","Twig\\Extension\\EscaperExtension","Twig\\Extension\\OptimizerExtension","RedAnt\\TwigComponents\\Extension"]:7:4:2.14.6:0:\Twig\Template:0 ) ```

**Comment by cinamo** [comment]
OK, so I've been playing around with Wordpress a bit...

I ran `composer require twig/twig` and `composer require redant/twig-components` in the WP main dir. Then I added this to `functions.php` in the theme:

```
require __DIR__ . '/../../../vendor/autoload.php';

/* 
Set vars to respective locations
Results in:
     [site url]/wp-content/themes/my-theme/templates
     [site url]/wp-content/themes/my-theme/templates/components
*/
$templateDir = get_template_directory() . "/templates"; 
$componentsDir = get_template_directory() . "/templates/components";

// Setup the loader
$loader = new \Twig\Loader\FilesystemLoader($templateDir);
$loader->addPath($componentsDir, "Ui"); 
$twig = new \Twig\Environment($loader);

// Initialize Twig Components registry
$componentsRegistry = new \RedAnt\TwigComponents\Registry($twig);
$componentsRegistry->addComponent('ui.button', '@Ui/button.html.twig');

// Add the extension to your Twig environment
$componentsExtension = new \RedAnt\TwigComponents\Extension($componentsRegistry);
$twig->addExtension($componentsExtension);

$template = $twig->load('test.html.twig');
echo $template->render([]);
```

Just to make sure: in the template folder, I've added a `templates` folder and inside it, a `components` folder. The `template/test.html.twig` contains something like:

```
<html>
<body>
    {{ render_component('ui.button', { label: 'test' })}}
    {{ component.ui.button({ label: 'test' })}}
</body>
</html>
```

and the `templates/components/button.html.twig` contains the component for the button (see the docs).

That seems to work for me  — I see a few differences with respect to paths with your example (specifically, the component file location and extension). Both syntaxes for calling the button work for me.

Let me know if that helps!

**Comment by corydhmiller** [comment]
That got me there! I ended up keeping the `composer.json` in the theme folder and restructuring the folder stacks.

This actually pushed me in the right direction for connecting it through Timber as well. 

```
// functions.php

$Timber = new Timber\Timber();

add_filter('timber/twig', 'add_component_extension_to_timber');

/**
 * Adds functionality to Twig.
 * 
 * @param \Twig\Environment $twig The Twig environment.
 * @return \Twig\Environment
 */
function add_component_extension_to_timber($twig)
{
  $componentsDir = get_template_directory() . "/templates/components";

  $componentsRegistry = new \RedAnt\TwigComponents\Registry($twig);
  $componentsRegistry->addComponent('ui.button', $componentsDir . '/ui/elements/button.twig');

  $componentsExtension = new \RedAnt\TwigComponents\Extension($componentsRegistry);
  $twig->addExtension($componentsExtension);
  return $twig;
}
```

Not sure if there's any real cons to not registering a namespace but my brain was a bit friend to figure that out this morning.

I'll consider this closed, but if this is helpful for others wanting to use Twig + Timber + Twig Components, this might have been helpful.
